M48
; DRILL file {KiCad (6.0.6)} date Tue Aug 29 14:34:48 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-29T14:34:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X45.0Y-68.45
T2
X20.0Y-30.8
X20.0Y-144.8
X79.0Y-91.8
X138.975Y-91.8
X231.0Y-32.8
X231.0Y-144.8
T0
M30
